---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
#baseurl: "http://nice-chow.github.io/hugo_blog"
baseurl: "http://zhoulai.me"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
...
